[theme]
primaryColor = "#5B6ABF"       # Helvetia Blue
backgroundColor = "#E6E6FA"    # Grayish Lavender (lighter shade)
secondaryBackgroundColor = "#D8BFD8"  # Lighter Aconite Violet
textColor = "#333333"          # Dark Gray for text
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200 