[supervisord]
nodaemon=true
user=root
logfile=/app/logs/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock


[program:dashboard]
command=uv run python run_watchtower_dashboard.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/logs/dashboard.err.log
stdout_logfile=/app/logs/dashboard.out.log
startretries=3
stopasgroup=true
killasgroup=true

[program:etl_scheduler]
command=uv run python deployment/etl_scheduler.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/logs/scheduler.err.log
stdout_logfile=/app/logs/scheduler.out.log
startretries=3
stopasgroup=true
killasgroup=true
