"""Components module for Watchtower Streamlit Application."""

from web.fullstreamlit.components import (
    adhd_tab,
    admin_tab,
    ai_platforms_tab,
    allkeyshop_tab,
    anime_display,
    arxiv_papers,
    arxiv_search,
    aws_training_tab,
    azure_training_tab,
    chan_generals_tab,
    courses_tab,
    dev_communities_tab,
    ecommerce_tab,
    enhanced_arxiv_papers,
    enhanced_innovation_tab,
    events_tab,
    expatcircle_tab,
    games_tab,
    google_cloud_blog_tab,
    home_server_tab,
    monitoring_tab,
    museums_tab,
    news_tab,
    scavenging_tab,
    security_tab,
    shortcuts_tab,
    tech_events_tab,
    videos_tab,
)
