"""Scavenging tab component for the Watchtower Streamlit application.

This tab loads aggregated RSS entries generated by the goldigging_scavenging_etl.py script and
presents them in an interactive table. Each category (anime, audiobooks, courses, etc.) has its
own sub-tab.
"""

from pathlib import Path

import pandas as pd  # type: ignore
import streamlit as st

# Use centralized path setup and safe logger
from ._path_setup import get_safe_logger

DATA_DIR = Path("data/scavenging")


def _load_category_file(json_path: Path) -> pd.DataFrame:
    """Load a single JSON file into a DataFrame, returning an empty DataFrame on failure."""
    if not json_path.exists():
        return pd.DataFrame()
    try:
        data = pd.read_json(json_path)
        if not data.empty and "published" in data.columns:
            # Ensure published column is datetime for sorting
            data["published"] = pd.to_datetime(data["published"], errors="coerce")
        return data
    except ValueError:
        return pd.DataFrame()


def _discover_categories() -> dict[str, Path]:
    """Return a mapping of category name -> aggregated JSON path."""
    if not DATA_DIR.exists():
        return {}
    files = DATA_DIR.glob("*_rss_entries.json")
    return {f.stem.replace("_rss_entries", ""): f for f in files}


def render(logger=None):
    """Render the Scavenging tab."""
    if logger is None:
        logger = get_safe_logger("ScavengingTab")

    st.header("⛏️ Scavenging RSS Feeds")

    categories_map = _discover_categories()
    if not categories_map:
        st.info("No scavenging data found. Run the Scavenging ETL to populate data.")
        return

    tab_titles = [cat.capitalize() for cat in sorted(categories_map.keys())]
    tabs = st.tabs(tab_titles)

    for title, cat in zip(tabs, sorted(categories_map.keys()), strict=False):
        with title:
            df = _load_category_file(categories_map[cat])
            if df.empty:
                st.warning(f"No entries available for {cat}.")
                continue

            # Sort newest first
            if "published" in df.columns:
                df = df.sort_values(by="published", ascending=False)

            # Rename some columns for nicer display
            rename_map = {
                "title": "Título",
                "link": "Enlace",
                "published": "Publicado",
                "summary": "Resumen",
                "source": "Fuente",
            }
            existing_columns = [c for c in rename_map if c in df.columns]
            df_display = df[existing_columns].rename(columns=rename_map)

            st.write(f"Mostrando {len(df_display)} elementos para {cat.capitalize()}")
            st.data_editor(
                df_display,
                hide_index=True,
                use_container_width=True,
                disabled=True,
                column_config={
                    "Enlace": st.column_config.LinkColumn(
                        label="Enlace", display_text="Abrir", width="small"
                    ),
                },
            )

            st.markdown("---")
            col1, col2 = st.columns(2)
            with col1:
                st.download_button(
                    label="📥 Descargar CSV",
                    data=df.to_csv(index=False).encode("utf-8"),
                    file_name=f"{cat}_scavenging.csv",
                    mime="text/csv",
                )
            with col2:
                st.download_button(
                    label="📥 Descargar JSON",
                    data=df.to_json(
                        orient="records", indent=2, force_ascii=False
                    ).encode("utf-8"),
                    file_name=f"{cat}_scavenging.json",
                    mime="application/json",
                )
