"""Base class and core logic for web content watchers.

This module provides the `BaseWatcher` abstract base class, which defines
the common interface and core functionality for all watcher implementations.
Watchers periodically check web pages for changes in specific values or content.
"""

from __future__ import annotations

import json
import time
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from src.utils.file_system import ensure_directories, get_project_root
from src.utils.logging import get_logger

try:
    from src.alerts.engine import AlertEngine
except ImportError:
    AlertEngine = None

from src.etl.proxy_manager import ProxyManager


class WatcherState:
    """State of a watcher."""

    def __init__(
        self,
        last_check: datetime | None = None,
        check_count: int = 0,
        event_count: int = 0,
        last_event_id: str = "",
        metadata: dict[str, Any] | None = None,
    ):
        self.last_check = last_check or datetime.now(timezone.utc)
        self.check_count = check_count
        self.event_count = event_count
        self.last_event_id = last_event_id
        self.metadata = metadata or {}


class WatcherEvent:
    """Event generated by a watcher."""

    def __init__(
        self,
        event_type: str,
        data: Any,
        timestamp: datetime | None = None,
        event_id: str | None = None,
    ):
        self.event_type = event_type
        self.data = data
        self.timestamp = timestamp or datetime.now(timezone.utc)
        self.event_id = event_id or f"{self.timestamp.timestamp()}_{event_type}"


class BaseWatcher(ABC):
    """Base class for all watchers.

    Watchers are processes that periodically check if a web page has changed
    with respect to some specific value or content. If a change is detected,
    they trigger an alarm.
    """

    def __init__(
        self,
        name: str,
        url: str,
        check_interval: int = 3600,
        max_retries: int = 3,
        retry_delay: int = 5,
    ):
        """Initialize the base watcher.

        Args:
            name: Unique name for this watcher
            url: URL to watch for changes
            check_interval: Time in seconds between checks (default: 1 hour)
            max_retries: Maximum number of retry attempts for network operations
            retry_delay: Initial delay in seconds between retries (exponential backoff)
        """
        self.name = name
        self.url = url
        self.check_interval = check_interval
        self.max_retries = max_retries
        self.retry_delay = retry_delay
        self.logger = get_logger(f"Watcher_{name}")

        # Initialize paths using pathlib
        self.project_root = Path(get_project_root())
        self.data_dir = self.project_root / "data" / "watchers" / self.name
        ensure_directories([f"data/watchers/{self.name}"])

        # Path to store the state file
        self.state_file = self.data_dir / "state.json"

        # Path to store events
        self.events_dir = self.data_dir / "events"
        ensure_directories([f"data/watchers/{self.name}/events"])

        # Initialize alert engine if available
        self.alert_engine: AlertEngine | None = None
        if AlertEngine is not None:
            try:
                self.alert_engine = AlertEngine()
                self.logger.debug(f"AlertEngine initialized for watcher {name}")
            except Exception as e:
                self.logger.warning(f"Failed to initialize AlertEngine for watcher {name}: {e}")

        self.proxy_manager = ProxyManager()

        # Load previous state if exists
        self.previous_state = self._load_state()

    def _load_state(self) -> dict[str, Any]:
        """Load the previous state from the state file.

        Returns:
            Dictionary containing the previous state
        """
        if self.state_file.exists():
            try:
                state_data = self.state_file.read_text(encoding="utf-8")
                return json.loads(state_data)
            except Exception as e:
                self.logger.error(f"Error loading state file: {e!s}")

        # Return empty state if file doesn't exist or can't be loaded
        return {
            "last_check": None,
            "last_value": None,
            "first_seen": datetime.now().isoformat(),
        }

    def _save_state(self, state: dict[str, Any]) -> None:
        """Save the current state to the state file.

        Args:
            state: State dictionary to save
        """
        try:
            state_json = json.dumps(state, indent=2, ensure_ascii=False)
            self.state_file.write_text(state_json, encoding="utf-8")
        except Exception as e:
            self.logger.error(f"Error saving state file: {e!s}")

    def _record_event(
        self,
        event_type: str,
        old_value: Any,
        new_value: Any,
        details: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Record a change event.

        Args:
            event_type: Type of event (e.g., 'change_detected')
            old_value: Previous value
            new_value: Current value
            details: Additional details about the event

        Returns:
            Dictionary containing the recorded event
        """
        timestamp = datetime.now()
        event_id = f"{timestamp.strftime('%Y%m%d%H%M%S')}_{event_type}"

        event = {
            "id": event_id,
            "type": event_type,
            "timestamp": timestamp.isoformat(),
            "watcher": self.name,
            "url": self.url,
            "old_value": old_value,
            "new_value": new_value,
            "details": details or {},
        }

        # Save event to file
        event_file = self.events_dir / f"{event_id}.json"
        try:
            event_json = json.dumps(event, indent=2, ensure_ascii=False)
            event_file.write_text(event_json, encoding="utf-8")
            self.logger.info(f"Event recorded: {event_id}")
        except Exception as e:
            self.logger.error(f"Error recording event: {e!s}")

        return event

    def fetch_page(self) -> str:
        """Fetch the page content with retry logic.

        Returns:
            HTML content of the page

        Raises:
            Exception: If the page cannot be fetched after all retries
        """
        last_exception = None

        session = self.proxy_manager.get_session()

        for attempt in range(self.max_retries):
            try:
                self.logger.info(f"Fetching {self.url} (attempt {attempt + 1}/{self.max_retries})")
                response = session.get(self.url, timeout=30)
                response.raise_for_status()
                return response.text

            except Exception as e:
                last_exception = e
                if attempt < self.max_retries - 1:
                    delay = self.retry_delay * (2**attempt)  # Exponential backoff
                    self.logger.warning(f"Error fetching URL {self.url}: {e!s}. Retrying in {delay}s... (attempt {attempt + 1}/{self.max_retries})")
                    time.sleep(delay)
                else:
                    self.logger.error(f"Failed to fetch URL {self.url} after {self.max_retries} attempts: {e!s}")

        if last_exception:
            raise last_exception

        raise RuntimeError(f"Failed to fetch {self.url} after {self.max_retries} retries")

    @abstractmethod
    def extract_value(self, html_content: str) -> Any:
        """Extract the value to watch from the HTML content.

        Must be implemented by subclasses.

        Args:
            html_content: HTML content of the page

        Returns:
            The extracted value
        """
        pass

    @abstractmethod
    def has_changed(self, old_value: Any, new_value: Any) -> bool:
        """Determine if the value has changed enough to trigger an alarm.

        Must be implemented by subclasses.

        Args:
            old_value: Previously extracted value
            new_value: Current extracted value

        Returns:
            True if the change should trigger an alarm, False otherwise
        """
        pass

    def trigger_alarm(self, old_value: Any, new_value: Any) -> None:
        """Trigger an alarm when a change is detected.

        Args:
            old_value: Previous value
            new_value: Current value
        """
        self.logger.warning(f"CHANGE DETECTED in {self.name}: {old_value} -> {new_value}")

        # Record the event
        self._record_event(event_type="change_detected", old_value=old_value, new_value=new_value)

        # Trigger alert engine evaluation if available
        if self.alert_engine:
            self._trigger_alert_evaluation(old_value, new_value)
        else:
            self.logger.debug("AlertEngine not available, skipping alert evaluation")

    def _trigger_alert_evaluation(self, old_value: Any, new_value: Any) -> None:
        """Trigger alert engine evaluation for new content.

        Args:
            old_value: Previous value
            new_value: Current value
        """
        try:
            # Prepare content dictionary for alert evaluation
            content = self._prepare_content_for_alerts(old_value, new_value)

            if content:
                # For now, use a default user ID. In multi-user setup (Epic 5),
                # this would be replaced with actual user IDs
                default_user_id = "default_user"

                # Evaluate content against alert rules (async to avoid blocking)
                alert_events = self.alert_engine.evaluate_content(content, default_user_id)

                if alert_events:
                    self.logger.info(f"Generated {len(alert_events)} alert events for watcher {self.name}")
                else:
                    self.logger.debug(f"No alert rules matched for watcher {self.name}")

        except Exception as e:
            self.logger.error(f"Error in alert evaluation for watcher {self.name}: {e}")

    def _prepare_content_for_alerts(self, old_value: Any, new_value: Any) -> dict[str, Any] | None:
        """Prepare content dictionary for alert engine evaluation.

        Args:
            old_value: Previous value
            new_value: Current value

        Returns:
            Content dictionary with alert-relevant fields, or None if not applicable
        """
        try:
            # Create content dictionary with metadata
            content = {
                "id": f"{self.name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
                "title": f"Change detected in {self.name}",
                "description": f"Value changed from {old_value} to {new_value}",
                "url": self.url,
                "source": self.name,
                "watcher_name": self.name,
                "timestamp": datetime.now().isoformat(),
                "old_value": old_value,
                "new_value": new_value,
                "event_type": "watcher_change",
                "categories": ["watcher", "change"],
                "tags": [self.name, "alert"],
            }

            # Add any additional metadata that might be useful for alert rules
            if hasattr(new_value, "__dict__"):
                # If new_value is an object, add its attributes
                content.update({k: v for k, v in new_value.__dict__.items() if not k.startswith("_") and isinstance(v, (str, int, float, bool, list))})

            return content

        except Exception as e:
            self.logger.error(f"Error preparing content for alerts: {e}")
            return None

    def check(self) -> None:
        """Check if the watched value has changed."""
        try:
            # Fetch the page
            html_content = self.fetch_page()

            # Extract the value
            current_value = self.extract_value(html_content)

            # Get current time
            now = datetime.now().isoformat()

            # Initialize state if first run
            if self.previous_state["last_value"] is None:
                self.logger.info(f"First check for {self.name}, value: {current_value}")
                new_state = {
                    "last_check": now,
                    "last_value": current_value,
                    "first_seen": self.previous_state["first_seen"],
                }
                self._save_state(new_state)
                return

            # Check if value has changed
            old_value = self.previous_state["last_value"]
            if self.has_changed(old_value, current_value):
                self.trigger_alarm(old_value, current_value)

            # Update state
            new_state = {
                "last_check": now,
                "last_value": current_value,
                "first_seen": self.previous_state["first_seen"],
            }
            self._save_state(new_state)
            self.previous_state = new_state

        except Exception as e:
            self.logger.error(f"Error checking watcher {self.name}: {e!s}")

    def run(self, continuous: bool = True, max_runs: int | None = None) -> None:
        """Run the watcher, either continuously or for a specified number of runs.

        Args:
            continuous: Whether to run continuously
            max_runs: Maximum number of runs if not continuous
        """
        self.logger.info(f"Starting watcher for {self.name} ({self.url})")

        run_count = 0

        try:
            while True:
                self.check()

                run_count += 1
                if not continuous or (max_runs is not None and run_count >= max_runs):
                    break

                self.logger.info(f"Sleeping for {self.check_interval} seconds")
                time.sleep(self.check_interval)

        except KeyboardInterrupt:
            self.logger.info("Watcher stopped by user")
        except Exception as e:
            self.logger.error(f"Watcher failed: {e!s}")
        finally:
            # Close any cached sessions to prevent connection pool leaks
            self.proxy_manager.close()

        self.logger.info(f"Watcher {self.name} finished after {run_count} runs")
