name: Docker Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -f deployment/Dockerfile \
            -t watchtower:${{ github.sha }} \
            -t watchtower:latest \
            .
